# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: example/v1/service.proto for package 'Example.V1'

require 'grpc'
require 'example/v1/service_pb'

module Example
  module V1
    module Service
      # Service says hello.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'example.v1.Service'

        # Hello the request in the response.
        rpc :Hello, ::Example::V1::HelloRequest, ::Example::V1::HelloResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
