#!/usr/bin/env bash

set -e

latest_tag=$(git tag | sort -V | tail -1)

# Build and push docker.
docker build --build-arg version="$latest_tag" -t alexfalkowski/go-service-template -t alexfalkowski/go-service-template:"$latest_tag" .
docker push alexfalkowski/go-service-template --all-tags
