#!/usr/bin/env bash

set -e

name=$(basename "$(pwd)")
user=$(whoami)

# Get all the submodules.
git submodule sync && git submodule update --init

# Clean up.
rm -rf vendor test/vendor go-service-template
make -C test clean-reports

# Replace name in files.
find "." -type f -exec sed -i "s/go-service-template/$name/g" {} +
find "." -type f -exec sed -i "s/example/$name/g" {} +

# Override test files.
find "test" -type f -name "*.rb" -exec sed -i "s/Example/${name^}/g" {} +
mv "test/lib/example.rb" "test/lib/$name.rb"

# Move service for API.
rm -f api/example/v1/*.go
rm -rf test/lib/example
mv api/example "api/$name"
sed -i "s/example\.v1/$name\.v1/g" "api/$name/v1/service.proto"
make -C api generate

# Fix style issues.
make dep && make format && make ruby-fix-lint

# Remove files that are not needed.
rm -rf "tools" "CHANGELOG.md"

# Create branch.
git checkout -b "$user/feat/init" && make msg="init $name" commit push review
