#!/usr/bin/env bash

set -e

readonly name=$1
readonly path=$2

# Clean up before we copy
rm -rf vendor test/vendor go-service-template
make -C test clean-reports

# Create the path if does not exist.
mkdir -p "$path"

# Copy all the files.
cp -R . "$path"

# Remove files that are not needed.
rm -rf "$path/.git" "${path:?}/bin" "$path/tools/new" "$path/CHANGELOG.md"

# Replace name in files.
find "$path" -type f -exec gsed -i "s/go-service-template/$name/g" {} +

# Override test files.
find "$path/test" -type f -name "*.rb" -exec gsed -i "s/Example/${name^}/g" {} +
find "$path/test" -type f -name "*.rb" -exec gsed -i "s/example/$name/g" {} +
mv "$path/test/lib/example.rb" "$path/test/lib/$name.rb"

# Move service for API.
mkdir -p "$path/api/$name/v1"
mv "$path/api/service/v1/service.proto" "$path/api/$name/v1/service.proto"
gsed -i "s/service/$name/g" "$path/api/$name/v1/service.proto"
rm -rf "$path/api/service"

# Setup git.
(cd "$path" && git init -q && git add -A && git commit -q -m "feat: setup with go-service-template")
(cd "$path" && git submodule -q add git@github.com:alexfalkowski/bin.git && git add -A && git commit -q --amend --no-edit)
